Update 001-electricity-meter-monitoring.zh-hans.md
taosdata/tdengine-modeling-and-querying-101 pull request #4
Opened 2022-06-29 08:26 UTC by fenghuazzm

1. 更新超链接 link；
2. 补充了建模语句。

2022-06-29 08:55 UTC, arielyang commented on cases/001-electricity-meter-monitoring.zh-hans.md
> +ALTER TABLE d1001 SET TAG  groupid = 1;
additional space

2022-06-29 08:55 UTC, arielyang commented on cases/001-electricity-meter-monitoring.zh-hans.md
> +describe meters;
All the SQL statements should be capitalized.

2022-06-29 08:56 UTC, ericyangpan commented on cases/001-electricity-meter-monitoring.zh-hans.md
> +describe meters;
All the SQL keywords should be capitalized.

2022-06-29 08:57 UTC, arielyang commented on cases/001-electricity-meter-monitoring.zh-hans.md
> +* 函数查询，[戳我查看 TDengine 支持的函数](https://docs.taosdata.com/taos-sql/function)。count(*) 函数只返回一列，first 、last 、last_row 函数返回全部列：
All the SQL keywords should be capitalized.

2022-06-29 08:59 UTC, arielyang commented on cases/001-electricity-meter-monitoring.zh-hans.md
> +详细介绍与部署操作请移步：[TDinsight - 基于Grafana的TDengine零依赖监控解决方案](https://docs.taosdata.com/reference/tdinsight/)
Space between Chinese char and English char is needed.

2022-06-29 09:00 UTC, arielyang requested changes
Need more changes

2022-06-29 09:10 UTC, fenghuazzm commented
Done

2022-06-29 09:15 UTC, arielyang requested changes
Need more changes

2022-06-29 09:15 UTC, arielyang commented on cases/001-electricity-meter-monitoring.zh-hans.md
> +* 函数查询，[戳我查看 TDengine 支持的函数](https://docs.taosdata.com/taos-sql/function)。COUNT(*) 函数只返回一列，FIRST 、LAST 、LAST_ROW 函数返回全部列：
additional space after FIRST & LAST.

2022-07-01 11:09 UTC, arielyang approved these changes

2022-07-01 11:10 UTC, arielyang approved these changes

2022-07-02 04:08 UTC, merged